[postgresql]
user = "u6turp8ahlrqme"
password = "pc72a46fbf12c0bc5e916bba2a1c4119be144f4727d69cf12bb418d3c83b9f06f"
host = "cdccpamhe0hpfj.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com"
port = "5432"
dbname = "d2019o3d90vvlt"